export const navLinks = [
    {
        title:"home",
        url:"/"
    },
    {
        title:"about",
        url:"/about"
    },
    {
        title:"FAQs",
        url:"/faq"
    },
    {
        title:"Events",
        url:"/events"
    },
    {
        title:"Contact",
        url:"/contact"
    },
]