name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version

    - name: Install dependencies
      run: npm install  # Adjust if using yarn or other package managers

    - name: Build project
      run: npm run build  # Adjust according to your build command

    - name: Install lftp
      run: sudo apt-get install lftp -y

    - name: Deploy to cPanel
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}       # FTP server address
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}   # FTP username
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}   # FTP password
      run: |
        lftp -c "
        open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER;
        mirror -R ./build /public_html;
        bye
        "
