name: Deploy to FTP

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.0  # Use the desired Node.js version

      - name: Install lftp
        run: sudo apt-get install lftp -y

      - name: Install dependencies and build Next.js app
        run: |
          yarn install  # Install project dependencies
          yarn build  # Build Next.js app

      - name: Deploy via FTP
        run: |
          lftp -c "
            set ftp:ssl-allow no;  # Disable SSL for FTP (adjust as needed)
            open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }};
            set ssl:verify-certificate no;  # Ignore certificate verification (adjust as needed)
            mirror -R -e -x .git/ -x .github/ -x .next/ -x node_modules/ ./ /public_html/;
            bye
          "
